(test
 (name matchbox_test)
 (libraries matchbox gpl alcotest core)
 (modules
  matchbox_test
  controller_tests
  synthesizer_tests
  interpreter_tests
  surface_synthesizer_tests
  surface_interpreter_tests
  classbench_parsing_tests
  acl_translation_tests)
 (action
  (run %{exe:matchbox_test.exe} --verbose)))

(test
 (name verifier_test)
 (libraries matchbox gpl alcotest core)
 (modules verifier_test)
 (action
  (run %{exe:verifier_test.exe})))

(test
 (name incremental_test)
 (libraries matchbox gpl alcotest core)
 (modules incremental_test)
 (action
  (run %{exe:incremental_test.exe})))

(test
 (name incremental_quickcheck_test)
 (libraries matchbox gpl alcotest core)
 (preprocess
  (pps ppx_jane))
 (modules incremental_quickcheck_test)
 (action
  (run %{exe:incremental_quickcheck_test.exe})))
